# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_serving/apis/configuration_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensorflow_serving.apis import configuration_pb2 as tensorflow__serving_dot_apis_dot_configuration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow_serving/apis/configuration_service.proto',
  package='tensorflow.serving',
  syntax='proto3',
  serialized_pb=_b('\n3tensorflow_serving/apis/configuration_service.proto\x12\x12tensorflow.serving\x1a+tensorflow_serving/apis/configuration.proto2x\n\x14\x43onfigurationService\x12`\n\tConfigure\x12(.tensorflow.serving.ConfigurationRequest\x1a).tensorflow.serving.ConfigurationResponseB\x03\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[tensorflow__serving_dot_apis_dot_configuration__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\370\001\001'))

_CONFIGURATIONSERVICE = _descriptor.ServiceDescriptor(
  name='ConfigurationService',
  full_name='tensorflow.serving.ConfigurationService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=120,
  serialized_end=240,
  methods=[
  _descriptor.MethodDescriptor(
    name='Configure',
    full_name='tensorflow.serving.ConfigurationService.Configure',
    index=0,
    containing_service=None,
    input_type=tensorflow__serving_dot_apis_dot_configuration__pb2._CONFIGURATIONREQUEST,
    output_type=tensorflow__serving_dot_apis_dot_configuration__pb2._CONFIGURATIONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONFIGURATIONSERVICE)

DESCRIPTOR.services_by_name['ConfigurationService'] = _CONFIGURATIONSERVICE

# @@protoc_insertion_point(module_scope)
